In [23]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [24]:
data = pd.read_csv("./data.csv", header=None)

In [25]:
data.columns = ["immse_stret","psnr_stret","immse_equal","psnr_equal"]
data["imagen"] = [
"barbaraD",
"barbaraL",
"hands1D",
"hands1L",
"lakeD",
"lakeL",
"LenaDark1",
"LenaDark2",
"LenaLight1",
"LenaLight2",
"peppersD",
"peppersL"]

In [26]:
data

    immse_stret  psnr_stret   immse_equal  psnr_equal      imagen
0   1413.759850   16.627047   3624.975876   12.537752    barbaraD
1    453.111294   21.568755   8498.407616    8.837428    barbaraL
2   3702.155195   12.446257    668.618242   19.879021     hands1D
3   2371.195286   14.381130  10072.011419    8.099642     hands1L
4   1217.868694   17.274799   1614.444462   16.050573       lakeD
5      0.000004  102.316203   5729.578087   10.549577       lakeL
6    762.095016   19.310712   1828.387802   15.510120   LenaDark1
7   1861.585587   15.431974   6042.361694   10.318736   LenaDark2
8   2144.765213   14.817006  10342.042236    7.984741  LenaLight1
9   1402.885391   16.660582   6409.154160   10.062796  LenaLight2
10  5261.385715   10.919802    158.509190   26.130259    peppersD
11    23.160137   34.483392   3620.747452   12.542821    peppersL